# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |cx|
  cx.vm.define :puppetdb do |config|
    config.vm.hostname = "vm-puppetdb"
    config.vm.box = "vm-puppetdb"
    config.vm.box_url = "http://puppet-vagrant-boxes.puppetlabs.com/ubuntu-server-12042-x64-vbox4210.box"
    #config.vm.box_url = "http://files.vagrantup.com/lucid32.box"

    config.vm.network :private_network, ip: "192.168.33.17"

    config.vm.synced_folder "/home/rahul/vm/puppetdb/home", "/x" #, :owner => '', :group=>'rahul'

    config.vm.provider :virtualbox do |vb|
       vb.gui = false
       vb.customize ["modifyvm", :id, "--memory", 32768]
       vb.customize ["modifyvm", :id, "--cpus", 4]
    end

    config.vm.provision :shell, :inline => "apt-get update --fix-missing"
    #config.vm.provision :puppet do |puppet|
    #   puppet.facter = { "fqdn" => "vm", "hostname" => "vm-puppetmaster" }
    #   puppet.manifests_path = "manifests"
    #   puppet.manifest_file  = "init.pp"
    #   puppet.module_path  = "modules"
    #end
    config.vm.provision :chef_solo do |chef|
      chef.node_name = 'vm-puppetdb'
      chef.cookbooks_path = ["cookbooks"]
      chef.add_recipe "puppetdb"
      chef.log_level = :debug
    end
  end
end
