# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |cx|
  cx.vm.define :bm1 do |config|
    config.vm.hostname = "vm-bm1"
    config.vm.box = "vm-bm1"
    config.vm.box_url = "http://puppet-vagrant-boxes.puppetlabs.com/ubuntu-server-12042-x64-vbox4210.box"
    config.vm.network :private_network, ip: "192.168.33.18"
    config.vm.synced_folder "/home/rahul/vm/bm/home", "/x" #, :owner => '', :group=>'rahul'
    config.vm.provider :virtualbox do |vb|
       vb.gui = false
       vb.customize ["modifyvm", :id, "--memory", 16384]
       vb.customize ["modifyvm", :id, "--cpus", 4]
    end
    config.vm.provision :shell, :inline => "apt-get update --fix-missing"
    config.vm.provision :chef_solo do |chef|
      chef.node_name = 'vm-bm1'
      chef.cookbooks_path = ["cookbooks"]
      chef.add_recipe "puppetdb"
      chef.log_level = :debug
    end
  end
  cx.vm.define :bm1 do |config|
    config.vm.hostname = "vm-bm2"
    config.vm.box = "vm-bm2"
    config.vm.box_url = "http://puppet-vagrant-boxes.puppetlabs.com/ubuntu-server-12042-x64-vbox4210.box"
    config.vm.network :private_network, ip: "192.168.33.19"
    config.vm.synced_folder "/home/rahul/vm/bm/home", "/x" #, :owner => '', :group=>'rahul'
    config.vm.provider :virtualbox do |vb|
       vb.gui = false
       vb.customize ["modifyvm", :id, "--memory", 16384]
       vb.customize ["modifyvm", :id, "--cpus", 4]
    end
    config.vm.provision :shell, :inline => "apt-get update --fix-missing"
    config.vm.provision :chef_solo do |chef|
      chef.node_name = 'vm-bm2'
      chef.cookbooks_path = ["cookbooks"]
      chef.add_recipe "puppetdb"
      chef.log_level = :debug
    end
  end

end
